<?php

use App\Mkg;
use Illuminate\Database\Seeder;

class MkgTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array("kode_mkg" => "00", "golongan_id" => 1),
            array("kode_mkg" => "01", "golongan_id" => 1),
            array("kode_mkg" => "02", "golongan_id" => 1),
            array("kode_mkg" => "03", "golongan_id" => 1),
            array("kode_mkg" => "04", "golongan_id" => 1),
            array("kode_mkg" => "05", "golongan_id" => 1),
            array("kode_mkg" => "06", "golongan_id" => 1),
            array("kode_mkg" => "07", "golongan_id" => 1),
            array("kode_mkg" => "08", "golongan_id" => 1),
            array("kode_mkg" => "09", "golongan_id" => 1),
            array("kode_mkg" => "10", "golongan_id" => 1),
            array("kode_mkg" => "11", "golongan_id" => 1),
            array("kode_mkg" => "12", "golongan_id" => 1),
            array("kode_mkg" => "13", "golongan_id" => 1),
            array("kode_mkg" => "14", "golongan_id" => 1),
            array("kode_mkg" => "15", "golongan_id" => 1),
            array("kode_mkg" => "00", "golongan_id" => 2),
            array("kode_mkg" => "01", "golongan_id" => 2),
            array("kode_mkg" => "02", "golongan_id" => 2),
            array("kode_mkg" => "03", "golongan_id" => 2),
            array("kode_mkg" => "04", "golongan_id" => 2),
            array("kode_mkg" => "05", "golongan_id" => 2),
            array("kode_mkg" => "06", "golongan_id" => 2),
            array("kode_mkg" => "07", "golongan_id" => 2),
            array("kode_mkg" => "08", "golongan_id" => 2),
            array("kode_mkg" => "09", "golongan_id" => 2),
            array("kode_mkg" => "00", "golongan_id" => 3),
            array("kode_mkg" => "01", "golongan_id" => 3),
            array("kode_mkg" => "02", "golongan_id" => 3),
            array("kode_mkg" => "03", "golongan_id" => 3),
            array("kode_mkg" => "04", "golongan_id" => 3),
            array("kode_mkg" => "05", "golongan_id" => 3),
            array("kode_mkg" => "06", "golongan_id" => 3),
            array("kode_mkg" => "07", "golongan_id" => 3),
            array("kode_mkg" => "00", "golongan_id" => 4),
            array("kode_mkg" => "01", "golongan_id" => 4),
            array("kode_mkg" => "02", "golongan_id" => 4),
            array("kode_mkg" => "03", "golongan_id" => 4),
            array("kode_mkg" => "04", "golongan_id" => 4),
            array("kode_mkg" => "05", "golongan_id" => 4),
            array("kode_mkg" => "06", "golongan_id" => 4),
            array("kode_mkg" => "07", "golongan_id" => 4),
            array("kode_mkg" => "00", "golongan_id" => 5),
            array("kode_mkg" => "01", "golongan_id" => 5),
            array("kode_mkg" => "02", "golongan_id" => 5),
            array("kode_mkg" => "03", "golongan_id" => 5),
            array("kode_mkg" => "04", "golongan_id" => 5),
            array("kode_mkg" => "05", "golongan_id" => 5),
            array("kode_mkg" => "06", "golongan_id" => 5),
            array("kode_mkg" => "07", "golongan_id" => 5),
            array("kode_mkg" => "00", "golongan_id" => 6),
            array("kode_mkg" => "01", "golongan_id" => 6),
            array("kode_mkg" => "02", "golongan_id" => 6),
            array("kode_mkg" => "03", "golongan_id" => 6),
            array("kode_mkg" => "04", "golongan_id" => 6),
            array("kode_mkg" => "05", "golongan_id" => 6),
            array("kode_mkg" => "06", "golongan_id" => 6),
            array("kode_mkg" => "00", "golongan_id" => 7),
            array("kode_mkg" => "01", "golongan_id" => 7),
            array("kode_mkg" => "02", "golongan_id" => 7),
            array("kode_mkg" => "03", "golongan_id" => 7),
            array("kode_mkg" => "04", "golongan_id" => 7),
            array("kode_mkg" => "05", "golongan_id" => 7),
            array("kode_mkg" => "06", "golongan_id" => 7),
            array("kode_mkg" => "00", "golongan_id" => 8),
            array("kode_mkg" => "01", "golongan_id" => 8),
            array("kode_mkg" => "02", "golongan_id" => 8),
            array("kode_mkg" => "03", "golongan_id" => 8),
            array("kode_mkg" => "04", "golongan_id" => 8),
            array("kode_mkg" => "05", "golongan_id" => 8),
            array("kode_mkg" => "06", "golongan_id" => 8),
            array("kode_mkg" => "07", "golongan_id" => 8),
            array("kode_mkg" => "08", "golongan_id" => 8),
            array("kode_mkg" => "09", "golongan_id" => 8),
            array("kode_mkg" => "10", "golongan_id" => 8),
            array("kode_mkg" => "11", "golongan_id" => 8),
            array("kode_mkg" => "12", "golongan_id" => 8),
            array("kode_mkg" => "13", "golongan_id" => 8),
            array("kode_mkg" => "14", "golongan_id" => 8),
            array("kode_mkg" => "00", "golongan_id" => 9),
            array("kode_mkg" => "01", "golongan_id" => 9),
            array("kode_mkg" => "02", "golongan_id" => 9),
            array("kode_mkg" => "03", "golongan_id" => 9),
            array("kode_mkg" => "04", "golongan_id" => 9),
            array("kode_mkg" => "05", "golongan_id" => 9),
            array("kode_mkg" => "06", "golongan_id" => 9),
            array("kode_mkg" => "07", "golongan_id" => 9),
            array("kode_mkg" => "08", "golongan_id" => 9),
            array("kode_mkg" => "09", "golongan_id" => 9),
            array("kode_mkg" => "10", "golongan_id" => 9),
            array("kode_mkg" => "11", "golongan_id" => 9),
            array("kode_mkg" => "00", "golongan_id" => 10),
            array("kode_mkg" => "01", "golongan_id" => 10),
            array("kode_mkg" => "02", "golongan_id" => 10),
            array("kode_mkg" => "03", "golongan_id" => 10),
            array("kode_mkg" => "04", "golongan_id" => 10),
            array("kode_mkg" => "05", "golongan_id" => 10),
            array("kode_mkg" => "06", "golongan_id" => 10),
            array("kode_mkg" => "07", "golongan_id" => 10),
            array("kode_mkg" => "08", "golongan_id" => 10),
            array("kode_mkg" => "09", "golongan_id" => 10),
            array("kode_mkg" => "10", "golongan_id" => 10),
            array("kode_mkg" => "00", "golongan_id" => 11),
            array("kode_mkg" => "01", "golongan_id" => 11),
            array("kode_mkg" => "02", "golongan_id" => 11),
            array("kode_mkg" => "03", "golongan_id" => 11),
            array("kode_mkg" => "04", "golongan_id" => 11),
            array("kode_mkg" => "05", "golongan_id" => 11),
            array("kode_mkg" => "06", "golongan_id" => 11),
            array("kode_mkg" => "07", "golongan_id" => 11),
            array("kode_mkg" => "00", "golongan_id" => 12),
            array("kode_mkg" => "01", "golongan_id" => 12),
            array("kode_mkg" => "02", "golongan_id" => 12),
            array("kode_mkg" => "03", "golongan_id" => 12),
            array("kode_mkg" => "04", "golongan_id" => 12),
            array("kode_mkg" => "05", "golongan_id" => 12),
            array("kode_mkg" => "06", "golongan_id" => 12),
            array("kode_mkg" => "07", "golongan_id" => 12),
            array("kode_mkg" => "08", "golongan_id" => 12),
            array("kode_mkg" => "09", "golongan_id" => 12),
            array("kode_mkg" => "10", "golongan_id" => 12),
            array("kode_mkg" => "11", "golongan_id" => 12),
            array("kode_mkg" => "00", "golongan_id" => 13),
            array("kode_mkg" => "01", "golongan_id" => 13),
            array("kode_mkg" => "02", "golongan_id" => 13),
            array("kode_mkg" => "03", "golongan_id" => 13),
            array("kode_mkg" => "04", "golongan_id" => 13),
            array("kode_mkg" => "05", "golongan_id" => 13),
            array("kode_mkg" => "06", "golongan_id" => 13),
            array("kode_mkg" => "07", "golongan_id" => 13),
            array("kode_mkg" => "08", "golongan_id" => 13),
            array("kode_mkg" => "09", "golongan_id" => 13),
            array("kode_mkg" => "10", "golongan_id" => 13),
            array("kode_mkg" => "00", "golongan_id" => 14),
            array("kode_mkg" => "01", "golongan_id" => 14),
            array("kode_mkg" => "02", "golongan_id" => 14),
            array("kode_mkg" => "03", "golongan_id" => 14),
            array("kode_mkg" => "04", "golongan_id" => 14),
            array("kode_mkg" => "05", "golongan_id" => 14),
            array("kode_mkg" => "06", "golongan_id" => 14),
            array("kode_mkg" => "00", "golongan_id" => 15),
            array("kode_mkg" => "01", "golongan_id" => 15),
            array("kode_mkg" => "02", "golongan_id" => 15),
            array("kode_mkg" => "03", "golongan_id" => 15),
            array("kode_mkg" => "04", "golongan_id" => 15),
            array("kode_mkg" => "05", "golongan_id" => 15),
            array("kode_mkg" => "06", "golongan_id" => 15),
            array("kode_mkg" => "07", "golongan_id" => 15),
            array("kode_mkg" => "08", "golongan_id" => 15),
            array("kode_mkg" => "09", "golongan_id" => 15),
            array("kode_mkg" => "00", "golongan_id" => 16),
            array("kode_mkg" => "01", "golongan_id" => 16),
            array("kode_mkg" => "02", "golongan_id" => 16),
            array("kode_mkg" => "03", "golongan_id" => 16),
            array("kode_mkg" => "04", "golongan_id" => 16),
            array("kode_mkg" => "05", "golongan_id" => 16),
            array("kode_mkg" => "06", "golongan_id" => 16),
        );

        Mkg::insert($data);
    }
}
